name: "Setup for SpringAI Multi-Module Tests"
description: "Setup For SpringAI Multi-Module Tests"

inputs:
  modules:
    description: "Comma-separated list of modules to test"
    required: true
  maven-properties:
    description: "Maven properties to pass to the build"
    required: false
    default: ""
  spring-ai-branch:
    description: "Spring AI branch to test"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check environment
      uses: actions/github-script@v7
      with:
        script: |
          const env = ${{ toJson(env) }}
          const emptyEnvEntries = Object.entries(env).filter(e => e[1].length === 0)
          emptyEnvEntries.length > 0 &&
            core.setFailed('Missing value for environment variable(s): ' + emptyEnvEntries.map(e => e[0]).join(', '));

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        repository: spring-projects/spring-ai
        ref: ${{ inputs.spring-ai-branch }}
        path: spring-ai

    - name: Determine JDK version
      id: jdk-version
      shell: bash
      run: |
        if [ "${{ inputs.spring-ai-branch }}" = "main" ]; then
          echo "version=25" >> $GITHUB_OUTPUT
        else
          echo "version=17" >> $GITHUB_OUTPUT
        fi

    - name: Set up JDK ${{ steps.jdk-version.outputs.version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ steps.jdk-version.outputs.version }}
        distribution: 'temurin'
        cache: maven

    - name: Install
      shell: bash
      run: cd spring-ai && echo 'Running with maven properties:' ${{ inputs.maven-properties }} && ./mvnw -ntp install -DskipTests ${{ inputs.maven-properties }}

    - name: Run integration tests
      shell: bash
      run: cd spring-ai && echo 'Running with maven properties:' ${{ inputs.maven-properties }} && ./mvnw -ntp -pl ${{ inputs.modules }} -Pintegration-tests ${{ inputs.maven-properties }} -Dfailsafe.rerunFailingTestsCount=2 verify