name: Model Test Template

on:
  workflow_call:


jobs:
  run-model-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-ai
          ref: refs/heads/main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install
        run: ./mvnw install -DskipTests
