name: Spring AI Integration Tests (Manual Only)
run-name: Spring AI Integration Tests (Manual Only)
on:
  - workflow_dispatch

jobs:
  test-minimax:
    env:
      MINIMAX_API_KEY: ${{ secrets.MINIMAX_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the action
        uses: actions/checkout@v4

      - name: Integration Test
        uses: ./.github/actions/do-integration-test
        with:
          model-name: minimax

  test-moonshot:
    env:
      MOONSHOT_API_KEY: ${{ secrets.MOONSHOT_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the action
        uses: actions/checkout@v4

      - name: Integration Test
        uses: ./.github/actions/do-integration-test
        with:
          model-name: moonshot

  test-qianfan:
    env:
      QIANFAN_API_KEY: ${{ secrets.QIANFAN_API_KEY }}
      QIANFAN_SECRET_KEY: ${{ secrets.QIANFAN_SECRET_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the action
        uses: actions/checkout@v4

      - name: Integration Test
        uses: ./.github/actions/do-integration-test
        with:
          model-name: qianfan

  test-zhipu-ai:
    env:
      ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the action
        uses: actions/checkout@v4

      - name: Integration Test
        uses: ./.github/actions/do-integration-test
        with:
          model-name: zhipu

  test-autoconfigure:
    env:
      MINIMAX_API_KEY: ${{ secrets.MINIMAX_API_KEY }}
      MOONSHOT_API_KEY: ${{ secrets.MOONSHOT_API_KEY }}
      QIANFAN_API_KEY: ${{ secrets.QIANFAN_API_KEY }}
      QIANFAN_SECRET_KEY: ${{ secrets.QIANFAN_SECRET_KEY }}
      ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the action
        uses: actions/checkout@v4

      - name: Autoconfigure Test
        uses: ./.github/actions/do-autoconfigure-test
