name: Spring AI Integration Tests (Manual Only)
run-name: Spring AI Integration Tests (Manual Only)
on:
  - workflow_dispatch

jobs:
  test-minimax:
    env:
      MINIMAX_API_KEY: ${{ secrets.MINIMAX_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        uses: actions/github-script@v7
        with:
          script: |
            const env = ${{ toJson(env) }}
            const emptyEnvEntries = Object.entries(env).filter(e => e[1].length === 0)
            emptyEnvEntries.length > 0 &&
              core.setFailed('Missing value for environment variable(s): ' + emptyEnvEntries.map(e => e[0]).join(', '));

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-ai
          ref: refs/heads/main
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install
        run: ./mvnw install -DskipTests
      - name: Run MiniMax model tests
        run: ./mvnw -pl models/spring-ai-minimax -Pintegration-tests -Dfailsafe.rerunFailingTestsCount=2 verify

  test-moonshot:
    env:
      MOONSHOT_API_KEY: ${{ secrets.MOONSHOT_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        uses: actions/github-script@v7
        with:
          script: |
            const env = ${{ toJson(env) }}
            const emptyEnvEntries = Object.entries(env).filter(e => e[1].length === 0)
            emptyEnvEntries.length > 0 &&
              core.setFailed('Missing value for environment variable(s): ' + emptyEnvEntries.map(e => e[0]).join(', '));

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-ai
          ref: refs/heads/main
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install
        run: ./mvnw install -DskipTests
      - name: Run Moonshot model tests
        run: ./mvnw -pl models/spring-ai-moonshot -Pintegration-tests -Dfailsafe.rerunFailingTestsCount=2 verify

  test-qianfan:
    env:
      QIANFAN_API_KEY: ${{ secrets.QIANFAN_API_KEY }}
      QIANFAN_SECRET_KEY: ${{ secrets.QIANFAN_SECRET_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        uses: actions/github-script@v7
        with:
          script: |
            const env = ${{ toJson(env) }}
            const emptyEnvEntries = Object.entries(env).filter(e => e[1].length === 0)
            emptyEnvEntries.length > 0 &&
              core.setFailed('Missing value for environment variable(s): ' + emptyEnvEntries.map(e => e[0]).join(', '));

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-ai
          ref: refs/heads/main
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install
        run: ./mvnw install -DskipTests
      - name: Run Qianfan model tests
        run: ./mvnw -pl models/spring-ai-qianfan -Pintegration-tests -Dfailsafe.rerunFailingTestsCount=2 verify

  test-zhipu-ai:
    env:
      ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        uses: actions/github-script@v7
        with:
          script: |
            const env = ${{ toJson(env) }}
            const emptyEnvEntries = Object.entries(env).filter(e => e[1].length === 0)
            emptyEnvEntries.length > 0 &&
              core.setFailed('Missing value for environment variable(s): ' + emptyEnvEntries.map(e => e[0]).join(', '));

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-ai
          ref: refs/heads/main
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install
        run: ./mvnw install -DskipTests
      - name: Run Zhipu AI model tests
        run: ./mvnw -pl models/spring-ai-zhipu -Pintegration-tests -Dfailsafe.rerunFailingTestsCount=2 verify

  test-autoconfigure:
    env:
      MINIMAX_API_KEY: ${{ secrets.MINIMAX_API_KEY }}
      MOONSHOT_API_KEY: ${{ secrets.MOONSHOT_API_KEY }}
      QIANFAN_API_KEY: ${{ secrets.QIANFAN_API_KEY }}
      QIANFAN_SECRET_KEY: ${{ secrets.QIANFAN_SECRET_KEY }}
      ZHIPU_API_KEY: ${{ secrets.ZHIPU_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        uses: actions/github-script@v7
        with:
          script: |
            const env = ${{ toJson(env) }}
            const emptyEnvEntries = Object.entries(env).filter(e => e[1].length === 0)
            emptyEnvEntries.length > 0 &&
              core.setFailed('Missing value for environment variable(s): ' + emptyEnvEntries.map(e => e[0]).join(', '));

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: spring-projects/spring-ai
          ref: refs/heads/main
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install
        run: ./mvnw install -DskipTests
      - name: Run Spring Boot Autoconfigure tests
        run: ./mvnw -pl spring-ai-spring-boot-autoconfigure -Pintegration-tests -Dfailsafe.rerunFailingTestsCount=2 verify
